version: "3.9"

services:
  frontend:
    build: ./telegram_user_bot
    container_name: frontend
    networks:
      - app_network
    expose:
      - "80"

networks:
  app_network:
    external: true
