services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "4000:4000"
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    external: true
