# HTTP → HTTPS
server {
  listen 80;
  server_name front.itformanomberone.com;

  return 301 https://$host$request_uri;
}

# HTTPS
server {
  listen 443 ssl;
  server_name frontend.limonska.top;

  ssl_certificate /etc/ssl/cloudflare/cert.pem;
  ssl_certificate_key /etc/ssl/cloudflare/key.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}
