server {
  listen 80;
  server_name front.itformanomberone.com;

  # Редирект на HTTPS
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name front.itformanomberone.com;

  ssl_certificate /etc/letsencrypt/live/front.itformanomberone.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/front.itformanomberone.com/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  root /usr/share/nginx/html;
  index index.html index.htm;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
