# Редирект HTTP -> HTTPS
server {
  listen 80;
  server_name front.itformanomberone.com;
  return 301 https://$host$request_uri;
}

# Основной HTTPS-сервер
server {
  listen 443 ssl;
  server_name front.itformanomberone.com;

  ssl_certificate /etc/letsencrypt/live/front.itformanomberone.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/front.itformanomberone.com/privkey.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}
